### ISSUE TITLE
Site no longer matches source code on github

### ISSUE THREAD

**Issue by scottyallen** [RichardLitt/the-user-is-drunk#1]
My basic faith in the project is called into question. It appears the author has completely abandoned open source principles in the pursuit of drunken fame.  I demand an answer!

**Comment by RichardLitt** [comment]
I deleted `master`. The source has been on `gh-pages` for the past two years. 

You have been answered. Now I am going back to my scotch (or, in truth, my latte. Quit drinking months ago.)
