### ISSUE TITLE
The Life-Changing Magic of Tidying Up

### ISSUE THREAD

**Issue by vlillies** [RichardLitt/the-user-is-drunk#18]
This repo is cluttered. We should clean up and great things will happen. 

- `_sites` folder from a long forgotten jekyll build? 
- `scale.fix.js` I feel like this is probably not needed anymore. 
- visionary and herzog pics. Both great, but not used. 

Any objections?

**Comment by RichardLitt** [comment]
This... should be in a different repo?

Oh. You're not talking about the book.

No objections. Clean it up. Keep the photos; may be needed for other assets, and they're thematically from the same time.
