### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/the-user-is-drunk#4]
·         Appropriate keywords have not been chosen for targeting your website

·         Relevant Keywords are not listed organically in the SERPs

·         Authenticated and targeted links have not been optimized

·         Your CSS and JS files have not been minified

·         Meta Tags need  to be Optimized properly according to targeted pages

·         Images are not optimized which directly is increasing the page loading time

·         Gzip Compression is not used

·         Leverage Browser Caching by using fonts approved by Google

·         Meta Title needs to be optimized as this is the most vital part when it comes to Search Engine Rankings

**Comment by RichardLitt** [comment]
- Run Lighthouse Labs
- Google Page Speed insights: https://developers.google.com/speed/pagespeed/insights/?url=theuserisdrunk.com&tab=desktop

**Comment by vlillies** [comment]
The site ranks highly on both Lighthouse labs and pagespeed. I don't see any reason to optimize further. Thoughts?

**Comment by RichardLitt** [comment]
Works for me.
